### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by pablojrios** [pablojrios/gpt4-pdf-chatbot-langchain#1]
```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at Home (webpack-internal:///./pages/index.tsx:29:78)
    at main
    at MyApp (webpack-internal:///./pages/_app.tsx:14:18)
    at StyleRegistry (C:\Users\riosp\git-repos\gpt4-pdf-chatbot-langchain\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (C:\Users\riosp\git-repos\gpt4-pdf-chatbot-langchain\node_modules\next\dist\shared\lib\router\adapters.js:78:11)
    at AppContainer (C:\Users\riosp\git-repos\gpt4-pdf-chatbot-langchain\node_modules\next\dist\server\render.js:341:29)
    at AppContainerWithIsomorphicFiberStructure (C:\Users\riosp\git-repos\gpt4-pdf-chatbot-langchain\node_modules\next\dist\server\render.js:377:57)
    at div
    at Body (C:\Users\riosp\git-repos\gpt4-pdf-chatbot-langchain\node_modules\next\dist\server\render.js:677:21)
```

**Comment by pablojrios** [comment]
Fix was taken from commit https://github.com/mayooear/gpt4-pdf-chatbot-langchain/commit/4e10d90e9f3650ee0c00a605241f92339ae8a9e7 from repo https://github.com/davideuler/gpt4-pdf-chatbot-langchain-chromadb
